-- OpenSIM seed (auto-generated by src/lib/server/db/seed.ts).
-- Program: Ingeniería en Sistemas Computacionales
-- Plan: ISIC-2010-224
-- Total subjects: 42
-- Total credits (target): 260
-- Idempotent: catalog INSERTs use OR IGNORE; test-student
-- rows use OR REPLACE so the fixture is deterministic on rerun.

-- careers
INSERT OR IGNORE INTO careers (code, name, total_credits, total_semesters) VALUES ('ISIC-2010-224', 'Ingeniería en Sistemas Computacionales', 260, 9);
--> statement-breakpoint
INSERT OR IGNORE INTO specialties (code, career_code, name) VALUES ('ISIE-TDS-2024-01', 'ISIC-2010-224', 'Tecnologías para el Desarrollo de Software');
--> statement-breakpoint
INSERT OR IGNORE INTO specialties (code, career_code, name) VALUES ('ISIE-MCA-2023', 'ISIC-2010-224', 'Matemático Aplicado y Cómputo');
--> statement-breakpoint
-- subjects
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('calculo-diferencial', 'ACF-0901', 'Cálculo Diferencial', 1, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('calculo-diferencial', 'ACF-2301');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('fundamentos-programacion', 'SCC-1005', 'Fundamentos de Programación', 1, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('introduccion-ingenieria-sistemas', 'AEC-1008', 'Introducción a la Ingeniería en Sistemas Computacionales', 1, 2, 2, 4, 'Ingeniería', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('matematicas-discretas', 'AEC-1014', 'Matemáticas Discretas', 1, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('taller-etica', 'ACA-0907', 'Taller de Ética', 1, 2, 1, 3, 'Humanidades', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('fundamentos-investigacion', 'ACC-0906', 'Fundamentos de Investigación', 1, 2, 2, 4, 'Investigación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('calculo-integral', 'ACF-0902', 'Cálculo Integral', 2, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('calculo-integral', 'ACF-2302');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('calculo-integral', 'calculo-diferencial');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('algebra-lineal', 'ACF-0903', 'Álgebra Lineal', 2, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('algebra-lineal', 'ACF-2303');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('algebra-lineal', 'calculo-diferencial');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('programacion-orientada-objetos', 'SCC-1012', 'Programación Orientada a Objetos', 2, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-orientada-objetos', 'fundamentos-programacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-orientada-objetos', 'matematicas-discretas');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('estructura-datos', 'SCC-1013', 'Estructura de Datos', 2, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('estructura-datos', 'fundamentos-programacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('estructura-datos', 'matematicas-discretas');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('contabilidad-financiera', 'AEC-1020', 'Contabilidad Financiera', 2, 2, 2, 4, 'Administración', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('calculo-vectorial', 'ACF-0904', 'Cálculo Vectorial', 3, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('calculo-vectorial', 'ACF-2304');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('calculo-vectorial', 'calculo-integral');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('calculo-vectorial', 'algebra-lineal');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('analisis-algoritmos', 'SCC-1014', 'Análisis de Algoritmos', 3, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('analisis-algoritmos', 'estructura-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('programacion-visual', 'SCC-1015', 'Programación Visual', 3, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-visual', 'programacion-orientada-objetos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('fisica-general', 'ACF-0905', 'Física General', 3, 3, 2, 5, 'Ciencias', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('fisica-general', 'ACF-2305');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('fisica-general', 'calculo-integral');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('arquitectura-computadoras', 'SCC-1006', 'Arquitectura de Computadoras', 3, 3, 2, 5, 'Hardware', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('arquitectura-computadoras', 'fundamentos-programacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('ecuaciones-diferenciales', 'ACF-0906', 'Ecuaciones Diferenciales', 4, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('ecuaciones-diferenciales', 'ACF-2306');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('ecuaciones-diferenciales', 'calculo-vectorial');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('metodos-numericos', 'SCC-1017', 'Métodos Numéricos', 4, 2, 3, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('metodos-numericos', 'calculo-vectorial');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('metodos-numericos', 'algebra-lineal');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('base-datos', 'SCC-1021', 'Fundamentos de Bases de Datos', 4, 2, 3, 5, 'Datos', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('base-datos', 'estructura-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('circuitos-electricos', 'SCC-1007', 'Circuitos Eléctricos y Electrónicos', 4, 2, 3, 5, 'Hardware', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('circuitos-electricos', 'fisica-general');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('circuitos-electricos', 'arquitectura-computadoras');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('sistemas-operativos', 'SCC-1018', 'Sistemas Operativos', 4, 3, 2, 5, 'Software', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sistemas-operativos', 'arquitectura-computadoras');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sistemas-operativos', 'programacion-orientada-objetos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('variable-compleja', 'ACF-0907', 'Variable Compleja', 5, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('variable-compleja', 'ACF-2307');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('variable-compleja', 'ecuaciones-diferenciales');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('programacion-logica-funcional', 'SCC-1019', 'Programación Lógica y Funcional', 5, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('programacion-logica-funcional', 'SCC-1019-OLD');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-logica-funcional', 'programacion-orientada-objetos');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-logica-funcional', 'estructura-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('redes-computadoras', 'SCC-1020', 'Redes de Computadoras', 5, 3, 2, 5, 'Redes', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('redes-computadoras', 'sistemas-operativos');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('redes-computadoras', 'circuitos-electricos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('lenguajes-automatas', 'SCC-1022', 'Lenguajes y Autómatas', 5, 3, 2, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('lenguajes-automatas', 'matematicas-discretas');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('lenguajes-automatas', 'estructura-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('ingenieria-software', 'SCC-1023', 'Ingeniería de Software', 5, 3, 2, 5, 'Software', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('ingenieria-software', 'analisis-algoritmos');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('ingenieria-software', 'fundamentos-investigacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('probabilidad-estadistica', 'ACF-0908', 'Probabilidad y Estadística', 6, 3, 2, 5, 'Matemáticas', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('probabilidad-estadistica', 'ACF-2308');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('probabilidad-estadistica', 'calculo-integral');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('inteligencia-artificial', 'SCC-1024', 'Inteligencia Artificial', 6, 3, 2, 5, 'Inteligencia Artificial', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('inteligencia-artificial', 'programacion-logica-funcional');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('inteligencia-artificial', 'lenguajes-automatas');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('sistemas-informacion', 'SCC-1025', 'Sistemas de Información', 6, 3, 2, 5, 'Software', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sistemas-informacion', 'base-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sistemas-informacion', 'ingenieria-software');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sistemas-informacion', 'contabilidad-financiera');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('diseno-interfaces', 'SCC-1026', 'Diseño de Interfaces', 6, 2, 3, 5, 'Diseño', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('diseno-interfaces', 'programacion-visual');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('diseno-interfaces', 'ingenieria-software');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('graficacion', 'SCC-1027', 'Graficación', 7, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('graficacion', 'algebra-lineal');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('graficacion', 'programacion-visual');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('administracion-bases-datos', 'SCC-1028', 'Administración de Bases de Datos', 7, 2, 3, 5, 'Datos', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('administracion-bases-datos', 'base-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('administracion-bases-datos', 'sistemas-operativos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('taller-investigacion-1', 'ACA-0909', 'Taller de Investigación I', 7, 2, 2, 4, 'Investigación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('taller-investigacion-1', 'fundamentos-investigacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('taller-investigacion-1', 'ingenieria-software');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('taller-investigacion-2', 'ACA-0910', 'Taller de Investigación II', 8, 2, 2, 4, 'Investigación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('taller-investigacion-2', 'taller-investigacion-1');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('programacion-web', 'SCC-1029', 'Programación Web', 8, 2, 3, 5, 'Programación', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-web', 'programacion-visual');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('programacion-web', 'base-datos');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('gestion-proyectos-software', 'SCC-1031', 'Gestión de Proyectos de Software', 8, 2, 2, 4, 'Administración', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('gestion-proyectos-software', 'ingenieria-software');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('gestion-proyectos-software', 'sistemas-informacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('servicio-social', 'ACJ-0911', 'Servicio Social', 9, 0, 16, 16, 'Práctica Profesional', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('residencia-profesional', 'ACJ-0912', 'Residencia Profesional', 9, 0, 20, 20, 'Práctica Profesional', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('residencia-profesional', 'taller-investigacion-2');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('esp-tds-arquitectura', 'SCE-1001', 'TDS I — Arquitecturas de Software', 9, 3, 2, 5, 'Especialidad', 'ISIE-TDS-2024-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-tds-arquitectura', 'ingenieria-software');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-tds-arquitectura', 'sistemas-informacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('esp-tds-cloud', 'SCE-1002', 'TDS II — Cloud y Microservicios', 9, 3, 2, 5, 'Especialidad', 'ISIE-TDS-2024-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-tds-cloud', 'esp-tds-arquitectura');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-tds-cloud', 'redes-computadoras');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('esp-mca-optimizacion', 'SCE-2001', 'MCA I — Optimización y Modelado', 9, 3, 2, 5, 'Especialidad', 'ISIE-MCA-2023');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-mca-optimizacion', 'metodos-numericos');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-mca-optimizacion', 'probabilidad-estadistica');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, specialty_code) VALUES ('esp-mca-cripto', 'SCE-2002', 'MCA II — Criptografía y Seguridad', 9, 3, 2, 5, 'Especialidad', 'ISIE-MCA-2023');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-mca-cripto', 'esp-mca-optimizacion');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('esp-mca-cripto', 'matematicas-discretas');
--> statement-breakpoint
--> statement-breakpoint
-- student_profiles (test student)
INSERT OR REPLACE INTO student_profiles (control_number, full_name, curp, birth_state, career_code, specialty_code, current_semester, certified_average, arithmetic_average, passed_average, approved_credits, remaining_credits, completed_credits, in_progress_credits, advance_percentage, status, health_service, enrollment_period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'Ana Gabriela Hernández Ruiz', 'HERA000615MMNRZNA3', 'Michoacán', 'ISIC-2010-224', 'ISIE-TDS-2024-01', 7, 8.7, 8.6, 8.5, 175, 85, 175, 24, 67.3, 'Activo regular', 'IMSS', 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
-- student_progress (38 rows for <NUMERO DE CONTROL PURGADO>)
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'calculo-diferencial', 'APPROVED', 8.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'fundamentos-programacion', 'APPROVED', 9, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'introduccion-ingenieria-sistemas', 'APPROVED', 9.2, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'matematicas-discretas', 'APPROVED', 7.8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'taller-etica', 'APPROVED', 9.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'fundamentos-investigacion', 'APPROVED', 8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'calculo-integral', 'APPROVED', 7.5, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'algebra-lineal', 'APPROVED', 8, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'programacion-orientada-objetos', 'APPROVED', 8.7, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'estructura-datos', 'APPROVED', 7, 'REPETICION', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'contabilidad-financiera', 'APPROVED', 8.5, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'calculo-vectorial', 'APPROVED', 8.2, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'analisis-algoritmos', 'APPROVED', 8.8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'programacion-visual', 'APPROVED', 9, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'fisica-general', 'APPROVED', 7.2, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'arquitectura-computadoras', 'APPROVED', 8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'ecuaciones-diferenciales', 'APPROVED', 7.8, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'metodos-numericos', 'APPROVED', 8.5, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'base-datos', 'APPROVED', 9, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'circuitos-electricos', 'APPROVED', 7.5, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'sistemas-operativos', 'APPROVED', 8.8, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'variable-compleja', 'APPROVED', 7, 'REPETICION', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'programacion-logica-funcional', 'APPROVED', 8.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'redes-computadoras', 'APPROVED', 8.7, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'lenguajes-automatas', 'APPROVED', 8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'ingenieria-software', 'APPROVED', 9.2, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'probabilidad-estadistica', 'APPROVED', 8, 'ESPECIAL', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'inteligencia-artificial', 'APPROVED', 8.8, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'sistemas-informacion', 'APPROVED', 8.5, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'diseno-interfaces', 'APPROVED', 9, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'graficacion', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'administracion-bases-datos', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'taller-investigacion-1', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'programacion-web', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'gestion-proyectos-software', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'taller-investigacion-2', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'servicio-social', 'LOCKED', NULL, NULL, 'ENERO-JUNIO/2027');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('<NUMERO DE CONTROL PURGADO>', 'residencia-profesional', 'LOCKED', NULL, NULL, 'AGOSTO-DICIEMBRE/2027');
--> statement-breakpoint
--> statement-breakpoint
-- course_groups (8 groups)
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1027-1', 'graficacion', 'SCC-1027-A', 'DOC-005', 1);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1028-1', 'administracion-bases-datos', 'SCC-1028-A', 'DOC-002', 1);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-ACA0909-1', 'taller-investigacion-1', 'ACA-0909-A', 'DOC-007', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1029-1', 'programacion-web', 'SCC-1029-A', 'DOC-003', 1);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1031-1', 'gestion-proyectos-software', 'SCC-1031-A', 'DOC-001', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-ACA0910-1', 'taller-investigacion-2', 'ACA-0910-A', 'DOC-007', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1027-2', 'graficacion', 'SCC-1027-B', 'DOC-006 León', 1);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1028-2', 'administracion-bases-datos', 'SCC-1028-B', 'DOC-004', 1);
--> statement-breakpoint
--> statement-breakpoint
-- course_schedule_blocks (14 blocks)
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1027-1', 'L', '08:00', '10:00', 'Lab. Cómputo 3');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1027-1', 'X', '08:00', '10:00', 'Lab. Cómputo 3');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1028-1', 'M', '10:00', '12:00', 'Lab. Bases de Datos');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1028-1', 'J', '10:00', '12:00', 'Lab. Bases de Datos');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-ACA0909-1', 'V', '12:00', '14:00', 'Aula 12');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1029-1', 'M', '14:00', '16:00', 'Lab. Cómputo 1');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1029-1', 'V', '08:00', '10:00', 'Lab. Cómputo 1');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1031-1', 'L', '12:00', '14:00', 'Aula 8');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1031-1', 'J', '12:00', '14:00', 'Aula 8');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-ACA0910-1', 'X', '12:00', '14:00', 'Aula 4');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1027-2', 'L', '16:00', '18:00', 'Lab. Cómputo 2');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1027-2', 'X', '16:00', '18:00', 'Lab. Cómputo 2');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1028-2', 'M', '16:00', '18:00', 'Lab. Bases de Datos');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1028-2', 'J', '16:00', '18:00', 'Lab. Bases de Datos');
--> statement-breakpoint
--> statement-breakpoint
-- verification queries (informational, no-op)
SELECT COUNT(*) AS careers FROM careers;
--> statement-breakpoint
SELECT COUNT(*) AS specialties FROM specialties;
--> statement-breakpoint
SELECT COUNT(*) AS subjects FROM subjects;
--> statement-breakpoint
SELECT COUNT(*) AS aliases FROM subject_aliases;
--> statement-breakpoint
SELECT COUNT(*) AS prerequisites FROM subject_prerequisites;
--> statement-breakpoint
SELECT COUNT(*) AS progress_rows FROM student_progress;
--> statement-breakpoint
SELECT COUNT(*) AS groups_offered FROM course_groups;
--> statement-breakpoint
SELECT COUNT(*) AS schedule_blocks FROM course_schedule_blocks;
