-- OpenSIM seed (auto-generated by src/lib/server/db/seed.ts).
-- Career: ISIC-2010-224 — Ingeniería en Sistemas Computacionales
-- Institution: Instituto Tecnológico de Morelia
-- Plan: Plan de estudios por competencias actualizado 2016 (2017) (ESCOLARIZADA)
-- Plan version: ISIC-2010-224-VERIFIED-2026-10-07
-- Total subjects: 68
-- Total credits (target): 260
-- Idempotent: catalog INSERTs use OR IGNORE; test-student
-- rows use OR REPLACE so the fixture is deterministic on rerun.

-- careers
INSERT OR IGNORE INTO careers (code, name, total_credits, total_semesters) VALUES ('ISIC-2010-224', 'Ingeniería en Sistemas Computacionales', 260, 9);
--> statement-breakpoint
INSERT OR IGNORE INTO specialties (code, career_code, name) VALUES ('ISIE-TDD-2026-01', 'ISIC-2010-224', 'Desarrollo de Software');
--> statement-breakpoint
INSERT OR IGNORE INTO specialties (code, career_code, name) VALUES ('ISIE-SID-2026-01', 'ISIC-2010-224', 'Ciberseguridad');
--> statement-breakpoint
INSERT OR IGNORE INTO specialties (code, career_code, name) VALUES ('ISIE-TND-2026-01', 'ISIC-2010-224', 'Nube');
--> statement-breakpoint
-- subjects
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acf-0901', 'ACF-0901', 'Cálculo Diferencial', 1, 3, 2, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('acf-0901', 'ACF-2301');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aed-1285', 'AED-1285', 'Fundamentos de Programación', 1, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('aed-1285', 'SCD-1008');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aca-0907', 'ACA-0907', 'Taller de Ética', 1, 0, 4, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('aca-0907', 'ACH-2307');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aef-1041', 'AEF-1041', 'Matemáticas Discretas', 1, 3, 2, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sch-1024', 'SCH-1024', 'Taller de Administración', 1, 1, 3, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acc-0906', 'ACC-0906', 'Fundamentos de Investigación', 1, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acf-0902', 'ACF-0902', 'Cálculo Integral', 2, 3, 2, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aed-1286', 'AED-1286', 'Programación Orientada a Objetos', 2, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subject_aliases (subject_canonical_id, alias_code) VALUES ('aed-1286', 'SCD-1020');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aec-1008', 'AEC-1008', 'Contabilidad Financiera', 2, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aec-1058', 'AEC-1058', 'Química', 2, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acf-0903', 'ACF-0903', 'Álgebra Lineal', 2, 3, 2, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aef-1052', 'AEF-1052', 'Probabilidad y Estadística', 2, 3, 2, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acf-0904', 'ACF-0904', 'Cálculo Vectorial', 3, 3, 2, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aed-1026', 'AED-1026', 'Estructura de Datos', 3, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1005', 'SCC-1005', 'Cultura Empresarial', 3, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acd-0908', 'ACD-0908', 'Desarrollo Sustentable', 3, 2, 3, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1013', 'SCC-1013', 'Investigación de Operaciones', 3, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scf-1006', 'SCF-1006', 'Física General', 3, 3, 2, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('acf-0905', 'ACF-0905', 'Ecuaciones Diferenciales', 4, 3, 2, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1017', 'SCC-1017', 'Métodos Numéricos', 4, 2, 2, 4, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1027', 'SCD-1027', 'Tópicos Avanzados de Programación', 4, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aef-1031', 'AEF-1031', 'Fundamentos de Bases de Datos', 4, 3, 2, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1022', 'SCD-1022', 'Simulación', 4, 2, 3, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1018', 'SCD-1018', 'Principios Eléctricos y Aplicaciones Digitales', 4, 2, 3, 5, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1010', 'SCC-1010', 'Graficación', 5, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aec-1034', 'AEC-1034', 'Fundamentos de Telecomunicaciones', 5, 2, 2, 4, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aec-1061', 'AEC-1061', 'Sistemas Operativos', 5, 2, 2, 4, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sca-1025', 'SCA-1025', 'Taller de Base de Datos', 5, 0, 4, 4, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1007', 'SCC-1007', 'Fundamentos de Ingeniería de Software', 5, 2, 2, 4, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1003', 'SCD-1003', 'Arquitectura de Computadoras', 5, 2, 3, 5, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aeb-1055', 'AEB-1055', 'Programación Web', 6, 1, 4, 5, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1021', 'SCD-1021', 'Redes de Computadoras', 6, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sca-1026', 'SCA-1026', 'Taller de Sistemas Operativos', 6, 0, 4, 4, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scb-1001', 'SCB-1001', 'Administración de Bases de Datos', 6, 1, 4, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1011', 'SCD-1011', 'Ingeniería de Software', 6, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1014', 'SCC-1014', 'Lenguajes de Interfaz', 6, 2, 2, 4, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1004', 'SCD-1004', 'Conmutación y Enrutamiento en Redes de Datos', 7, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1015', 'SCD-1015', 'Lenguajes y Autómatas I', 7, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aca-0909', 'ACA-0909', 'Taller de Investigación I', 7, 0, 4, 4, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scg-1009', 'SCG-1009', 'Gestión de Proyectos de Software', 7, 3, 3, 6, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1023', 'SCC-1023', 'Sistemas Programables', 7, 2, 2, 4, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1019', 'SCC-1019', 'Programación Lógica y Funcional', 8, 2, 2, 4, NULL, 'INDEPENDENT', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sca-1002', 'SCA-1002', 'Administración de Redes', 8, 0, 4, 4, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('aca-0910', 'ACA-0910', 'Taller de Investigación II', 8, 0, 4, 4, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scd-1016', 'SCD-1016', 'Lenguajes y Autómatas II', 8, 2, 3, 5, NULL, 'SERIALIZED', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('scc-1012', 'SCC-1012', 'Inteligencia Artificial', 9, 2, 2, 4, NULL, 'UNKNOWN', 'GENERIC', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('itm-100', 'ITM-100', 'Tutoría', 1, 0, 0, 0, NULL, 'INDEPENDENT', 'COMPLEMENTARY', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('itm-104', 'ITM-104', 'Actividades Físicas para la Salud y la Prevención', 1, 0, 0, 0, NULL, 'INDEPENDENT', 'COMPLEMENTARY', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('itm-105', 'ITM-105', 'Apreciación de Artes y Diversidad Cultural', 2, 0, 0, 0, NULL, 'INDEPENDENT', 'COMPLEMENTARY', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('itm-101', 'ITM-101', 'Actividades Complementarias', 7, 0, 0, 0, NULL, 'INDEPENDENT', 'COMPLEMENTARY', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('itm-102', 'ITM-102', 'Servicio Social', 8, 0, 0, 10, NULL, 'INDEPENDENT', 'PRACTICE', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('itm-103', 'ITM-103', 'Residencia Profesional', 9, 0, 0, 10, NULL, 'INDEPENDENT', 'PRACTICE', NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sid-2301', 'SID-2301', 'SEGURIDAD EN INFRAESTRUCTURA', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-SID-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sid-2302', 'SID-2302', 'SEGURIDAD EN LA NUBE', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-SID-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sid-2303', 'SID-2303', 'HARDENING DE SERVIDORES', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-SID-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sid-2304', 'SID-2304', 'SEGURIDAD EN SERVICIOS', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-SID-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('sid-2305', 'SID-2305', 'AUDITORIA Y GESTION EN SEGURIDAD INFORMATICA', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-SID-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tdd-2301', 'TDD-2301', 'TOPICOS SELECTOS DE INGENIERIA DE SOFTWARE', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TDD-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tdd-2302', 'TDD-2302', 'SEGURIDAD DEL SOFTWARE', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TDD-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tdd-2303', 'TDD-2303', 'DISEÑO DE EXPERIENCIA DE USUARIO', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TDD-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tdd-2304', 'TDD-2304', 'TOPICOS SELECTOS DE TECNOLOGIAS WEB Y MOVIL', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TDD-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tdd-2305', 'TDD-2305', 'TECNOLOGIAS PARA SISTEMAS DE INTELIGENCIA DE NEGOCIOS', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TDD-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tnd-2301', 'TND-2301', 'INTEGRACION CONTINUA DE PROYECTOS WEB', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TND-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tnd-2302', 'TND-2302', 'APLICACIONES MOVILES', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TND-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tnd-2303', 'TND-2303', 'CIENCIA DE DATOS', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TND-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tnd-2304', 'TND-2304', 'INTERNET DE TODAS LAS COSAS', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TND-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tnd-2305', 'TND-2305', 'INFRAESTRUCTURA DE SERVICIOS', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TND-2026-01');
--> statement-breakpoint
INSERT OR IGNORE INTO subjects (canonical_id, code, name, semester, ht, hp, credits, area, seriation_state, component, specialty_code) VALUES ('tnd-2306', 'TND-2306', 'RECUPERACION DE INFORMACION DE LA WEB', NULL, NULL, NULL, 5, NULL, 'UNKNOWN', 'SPECIALTY', 'ISIE-TND-2026-01');
--> statement-breakpoint
-- subject_prerequisites
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('acf-0902', 'acf-0901');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('aed-1286', 'aed-1285');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('acf-0904', 'acf-0902');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('aed-1026', 'aed-1286');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scd-1027', 'aed-1026');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sca-1025', 'aef-1031');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scd-1021', 'aec-1034');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scb-1001', 'sca-1025');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scd-1011', 'scc-1007');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scd-1004', 'scd-1021');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scg-1009', 'scd-1011');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scc-1023', 'scc-1014');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('sca-1002', 'scd-1004');
--> statement-breakpoint
INSERT OR IGNORE INTO subject_prerequisites (subject_canonical_id, prerequisite_canonical_id) VALUES ('scd-1016', 'scd-1015');
--> statement-breakpoint
--> statement-breakpoint
-- student_profiles (test student)
INSERT OR REPLACE INTO student_profiles (control_number, full_name, curp, birth_state, career_code, specialty_code, current_semester, certified_average, arithmetic_average, passed_average, approved_credits, remaining_credits, completed_credits, in_progress_credits, advance_percentage, status, health_service, enrollment_period) VALUES ('12345678', 'Ana Gabriela Hernández Ruiz', 'HERA000615MMNRZNA3', 'Michoacán', 'ISIC-2010-224', 'ISIE-TDD-2026-01', 7, 8.7, 8.6, 8.5, 175, 85, 175, 24, 67.3, 'Activo regular', 'IMSS', 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
-- student_progress (49 rows for 12345678)
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aca-0907', 'APPROVED', 8.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acc-0906', 'APPROVED', 9, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acf-0901', 'APPROVED', 7.8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aed-1285', 'APPROVED', 9.2, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aef-1041', 'APPROVED', 8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'itm-100', 'APPROVED', NULL, NULL, 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'itm-104', 'APPROVED', NULL, NULL, 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'sch-1024', 'APPROVED', 7.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2022');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acf-0902', 'APPROVED', 8.7, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acf-0903', 'APPROVED', 7, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aec-1008', 'APPROVED', 8.5, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aec-1058', 'APPROVED', 8.2, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aed-1286', 'APPROVED', 8.8, 'ORDINARIO', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aef-1052', 'APPROVED', 9, 'REPETICION', 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'itm-105', 'APPROVED', NULL, NULL, 'ENERO-JUNIO/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acd-0908', 'APPROVED', 7.2, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acf-0904', 'APPROVED', 8, 'ESPECIAL', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aed-1026', 'APPROVED', 7.8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1005', 'APPROVED', 8.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1013', 'APPROVED', 9, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scf-1006', 'APPROVED', 7.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2023');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'acf-0905', 'APPROVED', 8.8, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aef-1031', 'APPROVED', 7, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1017', 'APPROVED', 8.5, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1018', 'APPROVED', 8.7, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1022', 'APPROVED', 8, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1027', 'APPROVED', 9.2, 'ORDINARIO', 'ENERO-JUNIO/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aec-1034', 'APPROVED', 8, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aec-1061', 'APPROVED', 8.8, 'REPETICION', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'sca-1025', 'APPROVED', 8.5, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1007', 'APPROVED', 9, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1010', 'APPROVED', 8.4, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1003', 'APPROVED', 7.6, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'tdd-2301', 'APPROVED', 8.9, 'ORDINARIO', 'AGOSTO-DICIEMBRE/2024');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aeb-1055', 'APPROVED', 9.3, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'sca-1026', 'APPROVED', 8.1, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scb-1001', 'APPROVED', 7.9, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1014', 'APPROVED', 8.6, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1011', 'APPROVED', 7.4, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1021', 'APPROVED', 8.8, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'tdd-2302', 'APPROVED', 9.1, 'ORDINARIO', 'ENERO-JUNIO/2025');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'aca-0909', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'itm-101', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scc-1023', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1004', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1015', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scg-1009', 'ENROLLED', NULL, NULL, 'AGOSTO-DICIEMBRE/2026');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'sca-1002', 'LOCKED', NULL, NULL, 'ENERO-JUNIO/2027');
--> statement-breakpoint
INSERT OR REPLACE INTO student_progress (student_control_number, subject_canonical_id, status, grade, evaluation_type, period) VALUES ('12345678', 'scd-1016', 'LOCKED', NULL, NULL, 'ENERO-JUNIO/2027');
--> statement-breakpoint
--> statement-breakpoint
-- course_groups (7 groups)
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCD1004-1', 'scd-1004', 'B7A', 'DOC-001', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCD1004-2', 'scd-1004', 'B7B', 'DOC-002', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCD1015-1', 'scd-1015', 'B7C', 'DOC-003', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-ACA0909-1', 'aca-0909', 'B7D', 'DOC-004', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCG1009-1', 'scg-1009', 'B7E', 'DOC-005', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCG1009-2', 'scg-1009', 'B7F', 'DOC-006', 0);
--> statement-breakpoint
INSERT OR REPLACE INTO course_groups (id, subject_canonical_id, group_code, teacher_name, has_lab) VALUES ('G-SCC1023-1', 'scc-1023', 'B5LA', 'DOC-007', 1);
--> statement-breakpoint
--> statement-breakpoint
-- course_schedule_blocks (14 blocks)
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCD1004-1', 'L', '08:00', '10:00', 'Lab. Redes');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCD1004-1', 'J', '08:00', '10:00', 'Lab. Redes');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCD1004-2', 'L', '10:00', '12:00', 'Lab. Redes');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCD1004-2', 'J', '10:00', '12:00', 'Lab. Redes');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCD1015-1', 'M', '10:00', '12:00', 'Aula 12');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCD1015-1', 'V', '10:00', '12:00', 'Aula 12');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-ACA0909-1', 'L', '12:00', '14:00', 'Aula 8');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-ACA0909-1', 'M', '12:00', '14:00', 'Aula 8');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCG1009-1', 'X', '14:00', '16:00', 'Aula 6');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCG1009-1', 'V', '14:00', '16:00', 'Aula 6');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCG1009-2', 'X', '16:00', '18:00', 'Aula 6');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCG1009-2', 'V', '16:00', '18:00', 'Aula 6');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1023-1', 'L', '16:00', '18:00', 'Lab. Electrónica');
--> statement-breakpoint
INSERT OR REPLACE INTO course_schedule_blocks (group_id, day, start_time, end_time, classroom) VALUES ('G-SCC1023-1', 'X', '16:00', '18:00', 'Lab. Electrónica');
--> statement-breakpoint
--> statement-breakpoint
-- verification queries (informational, no-op)
SELECT COUNT(*) AS careers FROM careers;
--> statement-breakpoint
SELECT COUNT(*) AS specialties FROM specialties;
--> statement-breakpoint
SELECT COUNT(*) AS subjects FROM subjects;
--> statement-breakpoint
SELECT COUNT(*) AS aliases FROM subject_aliases;
--> statement-breakpoint
SELECT COUNT(*) AS prerequisites FROM subject_prerequisites;
--> statement-breakpoint
SELECT COUNT(*) AS progress_rows FROM student_progress;
--> statement-breakpoint
SELECT COUNT(*) AS groups_offered FROM course_groups;
--> statement-breakpoint
SELECT COUNT(*) AS schedule_blocks FROM course_schedule_blocks;
